/* tslint:disable */
/* eslint-disable */
/**
 * Prism API
 * API for Prism project
 *
 * The version of the OpenAPI document: v1
 * Contact: mercysquadrant@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/artist-api';
export * from './api/auth-api';
export * from './api/authentication-api';
export * from './api/content-api';
export * from './api/following-api';
export * from './api/likes-api';
export * from './api/tags-api';
export * from './api/user-api';

