/* tslint:disable */
/* eslint-disable */
/**
 * Prism API
 * API for Prism project
 *
 * The version of the OpenAPI document: v1
 * Contact: mercysquadrant@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthLoginCreateRequest
 */
export interface AuthLoginCreateRequest {
    /**
     * Username or Email
     * @type {string}
     * @memberof AuthLoginCreateRequest
     */
    'username_or_email': string;
    /**
     * Password
     * @type {string}
     * @memberof AuthLoginCreateRequest
     */
    'password': string;
}

