/* tslint:disable */
/* eslint-disable */
/**
 * Prism API
 * API for Prism project
 *
 * The version of the OpenAPI document: v1
 * Contact: mercysquadrant@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthRegisterCreate400Response
 */
export interface AuthRegisterCreate400Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthRegisterCreate400Response
     */
    'username'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthRegisterCreate400Response
     */
    'email'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthRegisterCreate400Response
     */
    'password'?: Array<string>;
}

