/* tslint:disable */
/* eslint-disable */
/**
 * Prism API
 * API for Prism project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@prism.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthLogoutCreate200Response
 */
export interface AuthLogoutCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthLogoutCreate200Response
     */
    'message'?: string;
}

