/* tslint:disable */
/* eslint-disable */
/**
 * Prism API
 * API for Prism project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@prism.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Content } from './content';

/**
 * 
 * @export
 * @interface ContentList200Response
 */
export interface ContentList200Response {
    /**
     * 
     * @type {number}
     * @memberof ContentList200Response
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof ContentList200Response
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<Content>}
     * @memberof ContentList200Response
     */
    'results': Array<Content>;
}

