/* tslint:disable */
/* eslint-disable */
/**
 * Prism API
 * API for Prism project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@prism.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PublicUser } from './public-user';

/**
 * 
 * @export
 * @interface Content
 */
export interface Content {
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    'id'?: number;
    /**
     * 
     * @type {PublicUser}
     * @memberof Content
     */
    'artist'?: PublicUser;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'image'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Content
     */
    'nsfw'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'created_at'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof Content
     */
    'tags': Set<string>;
}

