/* tslint:disable */
/* eslint-disable */
/**
 * Prism API
 * API for Prism project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@prism.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Following
 */
export interface Following {
    /**
     * 
     * @type {number}
     * @memberof Following
     */
    'user': number;
    /**
     * 
     * @type {number}
     * @memberof Following
     */
    'artist': number;
    /**
     * 
     * @type {string}
     * @memberof Following
     */
    'created_at'?: string;
}

